/* Short, reviewable explanations complement the playable tutorial. */
(function(root){
  'use strict';
  function sections(config,data){const deckRules=typeof module==='object'&&module.exports?require('./deck-rules'):root.FrontlinesDeckRules;return {
    Winning:['Push the orange frontline toward the enemy command.','Capture the enemy home or control '+config.victoryTerritories+' territories. Card damage removes opposition; territory wins the match.'],
    'Turn structure':['On your offensive turn, units ready, Order spending resets and you draw cards.','You have '+config.actionLimit+' Command Actions. Deploy affordable free-command cards, then move or attack. End turn adds your objective forces’ Presence to capture progress and passes initiative. Combat responses briefly give the defender control.'],
    Capacity:['Capacity is the total force your command can support. Available Capacity pays for a card’s printed Presence cost.','Available = Capacity − Committed Presence − Orders spent. Survivors keep Presence committed. Destruction or recall frees commitment. Orders refresh on your next offensive turn. Capacity starts at '+config.startingCommand+', grows by '+config.commandGrowth+' on later turns and caps at '+config.commandCap+'.'],
    'Command Actions':['Command Actions pay for major battlefield decisions, separately from Capacity.','Ordinary deployment generally uses 0. Moving and initiating combat use 1. Heavy/leader deployments and tactical Orders marked 1 use both resources. A card marked 0 remains playable at zero Command Actions if Capacity, timing and slots permit. Responses and Counters use 0.'],
    Deployment:['Select a card, inspect its Capacity and Command Action costs, then choose highlighted owned territory.','Each side has '+config.slotsPerTerritory+' slots per territory. A unique commander cannot have a second copy deployed. New units can move; they need Rush to attack on the turn they enter.'],
    Combat:['Select your ready unit and an enemy in the same territory. Preview the exchange before choosing the target.','Attack damage is simultaneous after Response/Counter windows. Wounds persist. Guards can intercept; Precision bypasses interception. Hidden response cards can change the forecast. Units at zero Health are destroyed and release commitment.'],
    Territory:['The orange territory is the active objective. Ground tint and P1/P2 markers identify ownership.','At offensive turn end, printed Presence of your forces on the objective adds to your progress. At '+config.captureThreshold+' you capture. Enemy forces can still be present: pressure is an occupation race, not an empty-territory requirement. Removing enemy forces slows their race.'],
    Frontline:['Capturing advances the objective one territory toward the opponent.','Your movable survivors break through into open slots on the next objective. Overflow and assets can stay on your owned ground. Defending enemies on lost ground immediately retreat or are eliminated; enemy forces cannot remain behind the advancing front.'],
    Retreat:['Displaced defenders attempt one adjacent territory toward their own command.','The destination must be legal friendly ground with an open allied slot. Retreats resolve in stable unit order. Fixed assets cannot withdraw. No legal retreat means elimination and released Presence. The battlefield animation and action history explain the outcome.'],
    'Card types':['Units fight and move. Leaders add powerful support. Assets hold Presence and support a position but cannot move or attack.','Orders have action, Response or Counter timing. Their cost badge states Command Actions as well as Capacity. Printed rules and keywords determine each card’s exception.'],
    Deckbuilding:['Open Arsenal from the command menu. Duplicate a protected template or create your own faction deck. You can inspect every card; normal Play requires owned copies.','Use exactly '+deckRules.size+' cards from one faction, up to '+deckRules.maxCopies+' copies per card and '+deckRules.maxLeaders+' copies per Leader. Saved incomplete decks stay intact with acquisition guidance. Legality and ownership are separate: War Room and AI may use any legal deck. Cost curves and archetype tendencies describe your composition; AI intent is the strategy you choose for testing.'],
    Collection:['Fresh profiles own a playable starter deck for every faction. Complete ordinary matches to earn Credits; both wins and defeats advance your collection. Developer games, practice, simulations and short operations do not grant match rewards.','Open Collection & Packs to purchase gameplay-earned packs, inspect rarity odds and guaranteed slots, reveal cards quickly, craft missing copies with Supply, and select owned cosmetic treatments. Excess copies convert automatically into Supply.'],
    Mastery:['Cards in eligible completed decks accumulate mastery from matches and battlefield actions. Field-Worn, Battle-Hardened and Veteran appearances unlock at progression milestones.','Rarity and cosmetic appearance do not change stats, costs, abilities or legal copies. Full, Reduced and Minimal presentation and independent audio controls are available in Settings.'],
    'Arsenal tactics':['Armor reduces regular combat damage by 1 everywhere; Fortify adds its protection only on owned ground. Direct damage Orders can bypass both.','Mark adds 1 incoming regular combat damage until the target’s next offensive turn. Reinforce heals and grants temporary Armor until your next offensive turn. Neither stacks with itself. Adapt asks you to select one mode before choosing its target; the selected mode alone resolves.'],
    Keywords:Object.entries(data.GLOSSARY||{}).map(([name,text])=>name+' — '+text),
    Factions:['Stonewall holds and recovers ground. Bruiser applies frontal pressure. Syndicate coordinates efficient tools.','Nightwalker disrupts plans and times precision attacks. Rogue adapts, recycles value and stays mobile. Deck choices let each faction pursue different plans.'],
    'Learning tips':['When commands run out, check whether you can still deploy a 0-command card. Preserve Capacity for Responses if an attack is coming.','Before ending your turn, look at the capture forecast. A capture displaces defenders immediately. Hints can be disabled or reset in Settings → Learning. Tutorial remains available to replay.']
  };}
  const api={sections};if(typeof module==='object'&&module.exports)module.exports=api;root.FrontlinesFieldManual=api;
})(typeof globalThis==='object'?globalThis:this);
