/* Short, reviewable explanations complement the playable tutorial. */
(function(root){
  'use strict';
  function sections(config,data){const deckRules=typeof module==='object'&&module.exports?require('./deck-rules'):root.FrontlinesDeckRules;return {
    Winning:['Push the orange frontline toward the enemy command.','Capture the enemy home or control '+config.victoryTerritories+' territories. Card damage removes opposition; territory wins the match.'],
    'Action windows':['TURN N contains FIRST Player’s normal Action Window, then SECOND Player’s normal Action Window. The fixed initiative player goes first every Turn. End Action Window passes control; the Turn number stays the same after FIRST.','At your own Action Window start, your units ready, Order spending resets, Capacity grows and you draw. You have '+config.actionLimit+' Command Actions. These refresh only for the player starting their window. Responses and Counters are nested combat choices, never a new normal Action Window.','After SECOND ends, Turn-End resolution scores the surviving battlefield, resolves capture and retreats, then starts TURN N+1. Once per Turn means once across both normal Action Windows; once per Action Window follows the named player’s window.'],
    Capacity:['Capacity is the total force your command can support. Available Capacity pays for a card’s printed Presence cost.','Available = Capacity − Committed Presence − Orders spent. Survivors keep Presence committed. Destruction or recall frees commitment. Orders refresh on your next action window. Capacity starts at '+config.startingCommand+', grows by '+config.commandGrowth+' on later action windows and caps at '+config.commandCap+'.'],
    'Command Actions':['Command Actions pay for major battlefield decisions, separately from Capacity.','Ordinary deployment generally uses 0. Moving and initiating combat use 1. Heavy/leader deployments and tactical Orders marked 1 use both resources. A card marked 0 remains playable at zero Command Actions if Capacity, timing and slots permit. Responses and Counters use 0.'],
    Deployment:['Select a card, inspect its Capacity and Command Action costs, then choose highlighted owned territory.','Each side has '+config.slotsPerTerritory+' slots per territory. A unique Leader cannot have a second copy deployed. Your off-lane Commander is a separate deck assignment. New units can move; they need Rush to attack in the action window they enter.'],
    Commanders:['Choose exactly one Commander from your faction alongside your 26-card deck. All ten launch leaders and their foundation decks are available immediately.','The Commander panel stays outside the battlefield. Its passive works automatically under the printed conditions; its active uses the displayed Capacity and Command Action costs, legal targets and one use per match. A spent active never resets on window changes. Commanders are not lane cards, cannot be targeted or killed and commit no Presence.','Compare the two faction Commanders before building: their passive and active reward different card roles and playstyles. The guided tutorial demonstrates a real passive trigger, asks you to activate an ability, and then lets you choose a Commander for the training match.'],
    Combat:['Select your ready unit and an enemy in the same territory. Preview the exchange before choosing the target.','Attack damage is simultaneous after Response/Counter windows. Wounds persist. Guards can intercept; Precision bypasses interception. Hidden response cards can change the forecast. Units at zero Health are destroyed and release commitment.'],
    Territory:['The orange border and ◆ marker identify the active objective. P1/P2 banners identify owned ground; ◇ marks neutral ground.','Only after both normal Action Windows, surviving objective pressure is compared. The stronger side gains its pressure minus the opponent’s; equal pressure adds zero. Existing progress persists until capture. At '+config.captureThreshold+' progress the winning side captures, then defenders retreat and mobile survivors break through.','The Turn-End outlook is a projection, not a guaranteed capture. During FIRST, the opponent still gets SECOND before scoring. Protect your surviving force or remove opposing pressure. Ending FIRST applies no progress and cannot capture.'],
    Frontline:['Capturing advances the objective one territory toward the opponent.','Your movable survivors break through into open slots on the next objective. Overflow and assets can stay on your owned ground. Defending enemies on lost ground immediately retreat or are eliminated; enemy forces cannot remain behind the advancing front.'],
    Retreat:['Displaced defenders attempt one adjacent territory toward their own command.','The destination must be legal friendly ground with an open allied slot. Retreats resolve in stable unit order. Fixed assets cannot withdraw. No legal retreat means elimination and released Presence. The battlefield animation and action history explain the outcome.'],
    'Card types':['Units fight and move. Field Leaders are deployable support units; they are separate from the off-lane Commander. Assets hold Presence and support a position but cannot move or attack.','Orders have action, Response or Counter timing. Their cost badge states Command Actions as well as Capacity. Printed rules and keywords determine each card’s exception.'],
    Deckbuilding:['Open Arsenal from the command menu. Duplicate a protected template or create your own faction deck. You can inspect every card; normal Play requires owned copies.','Use exactly '+deckRules.size+' cards from one faction, up to '+deckRules.maxCopies+' copies per card and '+deckRules.maxLeaders+' copies per Leader. Saved incomplete decks stay intact with acquisition guidance. Legality and ownership are separate: War Room and AI may use any legal deck. Cost curves and archetype tendencies describe your composition; AI intent is the strategy you choose for testing.'],
    Collection:['Fresh profiles own a playable starter deck for every faction. Completed ordinary matches award 70 Credits for a win or 50 for a defeat, plus a one-time 50-Credit first-match bonus. Developer games, practice and simulations do not grant match rewards. Private online matches grant no Credits, Supply or packs.','Open Collection & Packs to purchase gameplay-earned packs, inspect rarity odds and guaranteed slots, reveal cards quickly, craft missing copies with Supply, and select owned cosmetic treatments. Excess copies convert automatically into Supply.'],
    'Private multiplayer':['Open Multiplayer, Host Private Match and send the invite code to a friend. Your friend opens Join Private Match and enters that code. Each commander selects their own faction, Commander and legal owned deck, then readies. The host starts when both players are ready.','Your force appears in the lower battlefield row and your hand stays visible while the opponent acts. Your Action Window permits commands; Waiting for the opponent permits inspection only. Combat Response and Counter windows belong to the player named in the command dock.','Brief connection interruptions pause the match and reconnect automatically. The same battlefield is restored before commands resume. Concede Match requires confirmation. Rematch returns both commanders to the lobby with previous selections; both Ready again. Private results retain eligible used-card mastery and history without economic rewards.'],
    Mastery:['Cards in eligible completed decks accumulate mastery from matches and battlefield actions. Field-Worn, Battle-Hardened and Veteran appearances unlock at progression milestones.','Rarity and cosmetic appearance do not change stats, costs, abilities or legal copies. Full, Reduced and Minimal presentation and independent audio controls are available in Settings.'],
    'Arsenal tactics':['Armor reduces regular combat damage by 1 everywhere; Fortify adds its protection only on owned ground. Direct damage Orders can bypass both.','Mark adds 1 incoming regular combat damage until the target’s next Action Window start. Reinforce heals and grants temporary Armor until the target’s next own Action Window. Sabotage disables printed traits until the target’s next own start. Neither stacks with itself. Adapt asks you to select one mode before choosing its target; the selected mode alone resolves.','Statuses show their expiry or consumption rule in the unit inspector and tooltip. Scavenge and Nothing Wasted share one eligible enemy-caused casualty draw per player per paired Turn. Voluntary Sacrifice is excluded; reclaim preserves wounds.'],
    Cover:[data.GLOSSARY?.Cover||'Cover reduces the next eligible direct enemy hit by 2, then is consumed. It does not stack and expires at its displayed action-window boundary.','Counter it with Breach or bypass it with Blast. Stonewall Trench Engineer and Dig In prepare a position; Rogue Jury-Rigged Shield pays for improvised protection.'],
    Breach:[data.GLOSSARY?.Breach||'Breach removes and ignores Cover on a direct attack; printed card rules define any bonus against Assets.','It is an attack property, not a stacking status or a permanent damage buff. Bruiser Demolition Squad and Linebreaker answer fortifications. Mobile units and unprepared ordinary troops avoid their specialized Asset bonus.'],
    Blast:[data.GLOSSARY?.Blast||'Blast targets a territory and damages a capped number of enemies in stable unit-ID order, bypassing Cover and Dodge.','The preview identifies affected enemies before execution. Moving units apart or destroying the source counters area value. Bruiser Frag Out hits up to two enemy permanents; Syndicate Coordinated Barrage rewards marked setup; Rogue Scrap Grenadier pays for a weaker blast.'],
    Dodge:[data.GLOSSARY?.Dodge||'Dodge deterministically avoids one eligible direct enemy attack, then is consumed; it does not stack and expires at its displayed action-window boundary.','Mark, Precision or Exposed counters the charge, and Blast bypasses it. Nightwalker Smoke Runner, Ghost Operative and Vanish create brief timing opportunities, never permanent untargetability.'],
    Suppression:[data.GLOSSARY?.Suppression||'Suppression applies −1 Attack and prevents voluntary movement through the end of the target’s next action window; refreshes but never stacks.','The unit can still attack, activate a legal ability or participate in normal play. Expiry, fighting in place and responses elsewhere provide counterplay. Bruiser Suppressor Heavy and Syndicate Suppression Team pay readiness and resources for tempo. Suppression is separate from Sabotage, which disables printed traits.'],
    Overwatch:[data.GLOSSARY?.Overwatch||'An eligible ready unit spends 1 Command Action and exhausts to watch its territory: first enemy voluntary movement or deployment there takes 2 direct damage, then the watch is consumed.','It expires at the watching side’s next action-window start. New units cannot arm it on deployment unless Rush or explicit card text allows it. Smoke blocks the reaction; removal and another route also answer it. Forced retreats and capture breakthroughs do not trigger it. Stonewall Bastion Gunner prepares fire; Nightwalker Shadow Trapper and Rogue Improvised Mine threaten entry visibly.'],
    Sacrifice:[data.GLOSSARY?.Sacrifice||'Sacrifice voluntarily destroys your own battlefield piece to pay an explicit cost; it is not an enemy-caused casualty.','The selected source and payoff are shown before a separate confirmation. It cannot trigger ordinary Scavenge or Nothing Wasted draws. Rogue Salvage Charge trades a real piece for Blast; Strip It for Parts trades one piece for paid repair. There is no duration or stacking benefit: the piece is destroyed once.'],
    Exposed:[data.GLOSSARY?.Exposed||'Exposed removes Cover and Dodge and adds +1 to the next qualifying direct enemy hit, then is consumed; it does not stack and expires at its displayed action-window boundary.','Avoid the prepared direct hit, use a different territory or let the timing expire. Syndicate Target Package sets up coordinated damage; Nightwalker Expose the Opening punishes wounded or exhausted units. Blast does not consume the direct-hit charge.'],
    Smoke:[data.GLOSSARY?.Smoke||'Smoke is a temporary territory effect: reduces direct enemy damage to the creating side’s units there by 1 and blocks Overwatch reactions in that territory.','It does not stack for the same side and expires at that side’s next action-window start. Blast bypasses its protection; Mark targeting stays legal. Nightwalker Smoke Screen buys a local timing opportunity without hiding or disabling units.'],
    Keywords:Object.entries(data.GLOSSARY||{}).map(([name,text])=>name+' — '+text),
    Factions:['Stonewall holds and recovers ground. Bruiser applies frontal pressure. Syndicate coordinates efficient tools.','Nightwalker disrupts plans and times precision attacks. Rogue adapts, recycles value and stays mobile. Deck choices let each faction pursue different plans.'],
    'Learning tips':['When commands run out, check whether you can still deploy a 0-command card. Preserve Capacity for Responses if an attack is coming.','Before ending your Action Window, read the Turn-End outlook and whether the opponent still acts. A resolved capture displaces defenders immediately. Hints can be disabled or reset in Settings → Learning. The fourteen-lesson tutorial teaches a full paired Turn, Commander passive and active, then a real short operation.']
  };}
  const api={sections};if(typeof module==='object'&&module.exports)module.exports=api;root.FrontlinesFieldManual=api;
})(typeof globalThis==='object'?globalThis:this);
