'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const B=require('../balance.js'),Decks=require('../decks.js'),Catalog=require('../commanders.js');
const R=B.createRuntime('sprint15'),E=R.engine,D=R.data,L=Decks.forData(D),clone=x=>JSON.parse(JSON.stringify(x));
function game(factions=['stonewall','bruiser'],commanders,config={}){const decks=factions.map((f,i)=>({...L.starters().find(d=>d.faction===f),...(commanders?.[i]?{commanderId:commanders[i]}:{})}));return E.createGame({seed:1515,factions,decks,config:{startingCommand:100,commandCap:120,commandGrowth:10,drawCount:1,...config}});}
function add(s,id,owner=0,territory=3,extra={}){const u={uid:'fixture'+s.nextUid++,cardId:id,owner,territory,damage:0,ready:true,deployedTurn:0,deployedWindow:0,movedTurn:-1,movedWindow:-1,attackedWindow:-1,defendedWindow:-1,abilityWindow:-1,...extra};s.units.push(u);return u;}
function hand(s,id,owner=s.activePlayer){const h={uid:'fixture'+s.nextUid++,cardId:id};s.players[owner].hand.push(h);return h;}
function act(s,a){const r=E.dispatch(s,a,{events:true});assert.equal(r.ok,true,r.error);E.assertInvariants(r.state);return r;}
const end=s=>act(s,{type:'endTurn'}),unit=(s,uid)=>s.units.find(u=>u.uid===uid);
function attack(s,a,b){return act(act(s,{type:'attack',unitUid:a.uid,targetUid:b.uid}).state,{type:'respond',pass:true});}
function order(s,id,extra={}){const h=hand(s,id);return act(s,{type:'order',handUid:h.uid,...extra});}
function timing(s){return [s.turn,s.window,s.windowIndex,s.activePlayer,s.phase,s.lastCompletedWindow,s.lastResolvedTurn];}

test('new default profile preserves all numeric cards, effects, art and 35 decks while legacy profile is exact',()=>{
 const frozen=require('../docs/balance/sprint15-v1.2.0-baseline/source/balance.js'),old=B.dataFor('sprint12');assert.deepEqual(old,frozen.dataFor('sprint12'));assert.equal(B.DEFAULT_PROFILE,'sprint15');assert.equal(Object.keys(D.CARDS).length,155);
 for(const [id,c]of Object.entries(D.CARDS)){const a={...c},b={...old.CARDS[id]};delete a.rulesText;delete b.rulesText;assert.deepEqual(a,b,id);assert.doesNotMatch(c.rulesText,/offensive turn|at your turn start|first move each turn|per player per turn/);}
 assert.deepEqual(L.getDecks(),Decks.forData(old).getDecks());assert.equal(L.getDecks().length,35);for(const deck of L.getDecks())assert.equal(L.validate(deck).legal,true,deck.id);
 assert.deepEqual(JSON.parse(fs.readFileSync('balance/sprint15.json')),B.getProfiles().find(p=>p.id==='sprint15'));
});
test('paired clock starts FIRST, passes SECOND on same Turn, and resolves exactly once with fixed initiative',()=>{
 let s=game();assert.deepEqual(timing(s),[1,0,1,0,'ACTION_WINDOW',0,0]);const first=end(s);s=first.state;assert.deepEqual(timing(s),[1,1,2,1,'ACTION_WINDOW',1,0]);assert.equal(first.events.some(e=>e.type==='turnEndBegin'||e.type==='pressure'),false);
 const second=end(s);s=second.state;assert.deepEqual(timing(s),[2,0,3,0,'ACTION_WINDOW',2,1]);for(const type of ['turnEndBegin','turnEndComplete','turnStarted','windowStarted'])assert.equal(second.events.filter(e=>e.type===type).length,1,type);
 s=end(end(s).state).state;assert.deepEqual(timing(s),[3,0,5,0,'ACTION_WINDOW',4,2]);assert.equal(s.initiativePlayer,0);
});
test('draw, Capacity, readiness and actions refresh only at the entering owner window',()=>{
 let s=game();const a=add(s,'stonewall_rifles',0,2,{ready:false}),b=add(s,'bruiser_brawler',1,4,{ready:false});s.players[0].spent=3;s.players[1].spent=2;s.actionsLeft=0;const h=s.players.map(p=>p.hand.length);
 s=end(s).state;assert.equal(s.turn,1);assert.equal(s.players[0].spent,3);assert.equal(s.players[1].spent,0);assert.equal(s.players[0].hand.length,h[0]);assert.equal(s.players[1].hand.length,h[1]+1);assert.equal(unit(s,a.uid).ready,false);assert.equal(unit(s,b.uid).ready,true);assert.equal(s.actionsLeft,3);assert.deepEqual(s.players.map(p=>p.command),[100,100]);
 s=end(s).state;assert.equal(s.players[0].command,110);assert.equal(s.players[1].command,100);assert.equal(s.players[0].spent,0);assert.equal(s.players[0].hand.length,h[0]+1);assert.equal(unit(s,a.uid).ready,true);assert.deepEqual(s.players.map(p=>p.actionWindows),[2,1]);assert.deepEqual(s.players.map(p=>p.turns),[2,1]);assert.deepEqual(s.stats.actionWindows,[2,1]);
});
test('Response and Counter preserve initiating clock and normal budget then return to Action Window',()=>{
 let s=game(['syndicate','stonewall']);const a=add(s,'syndicate_enforcer'),b=add(s,'stonewall_defender',1),brace=hand(s,'stonewall_brace',1),counter=hand(s,'syndicate_counter',0);const context=timing(s).slice(0,4);
 s=act(s,{type:'attack',unitUid:a.uid,targetUid:b.uid}).state;assert.equal(s.phase,'RESPONSE');assert.deepEqual(timing(s).slice(0,4),context);assert.equal(s.actionsLeft,2);
 s=act(s,{type:'respond',handUid:brace.uid}).state;assert.equal(s.phase,'COUNTER');assert.deepEqual(timing(s).slice(0,4),context);assert.equal(s.actionsLeft,2);
 const r=act(s,{type:'counter',handUid:counter.uid});s=r.state;assert.equal(s.phase,'ACTION_WINDOW');assert.equal(s.response,null);assert.deepEqual(timing(s).slice(0,4),context);assert.equal(s.actionsLeft,2);assert.ok(r.events.every(e=>e.turn===1&&e.window===0&&e.windowIndex===1&&e.activePlayer===0));
});
test('invalid actions leave clock, RNG and all state untouched, and committed snapshots reject contradictory phases',()=>{
 let s=game();for(const a of [{type:'respond',pass:true},{type:'counter',pass:true},{type:'attack',unitUid:'missing',targetUid:'missing'},{type:'endTurn',player:1},{type:'unknown'}]){const before=clone(s),r=E.dispatch(s,a,{events:true});assert.equal(r.ok,false);assert.strictEqual(r.state,s);assert.deepEqual(s,before);assert.deepEqual(r.events,[]);}
 for(const change of [{activePlayer:1},{window:1},{phase:'TURN_END'},{lastResolvedTurn:1},{windowIndex:2}])assert.throws(()=>E.assertInvariants({...clone(s),...change}),/invariant/);
});
test('serializing ACTION/RESPONSE/COUNTER reproduces exact next authoritative transition with no hooks rerun',()=>{
 let s=game(['syndicate','stonewall']);const a=add(s,'syndicate_enforcer'),b=add(s,'stonewall_defender',1),h=hand(s,'stonewall_brace',1);
 for(const action of [{type:'attack',unitUid:a.uid,targetUid:b.uid},{type:'respond',handUid:h.uid},{type:'counter',pass:true},{type:'endTurn'},{type:'endTurn'}]){const expected=act(s,action),restored=act(clone(s),action);assert.deepEqual(restored,expected);s=expected.state;}
});
test('first-window pressure is provisional; opposing reinforcement before Turn End prevents apparent capture',()=>{
 let s=game(undefined,undefined,{captureThreshold:4}),a=add(s,'stonewall_heavy');const preview=E.captureOutlook(s);assert.equal(preview.capturePlayer,0);assert.equal(preview.opponentWindowPending,true);s=end(s).state;assert.equal(s.territories[3].owner,null);assert.deepEqual(s.territories[3].progress,[0,0]);add(s,'bruiser_rupture_heavy',1);const out=E.captureOutlook(s);assert.equal(out.opponentWindowPending,false);assert.deepEqual(out.gains,[0,2]);s=end(s).state;assert.equal(s.territories[3].owner,null);assert.deepEqual(s.territories[3].progress,[0,2]);assert.equal(unit(s,a.uid).territory,3);
});
test('net surviving pressure resolves once; ties add zero; accumulated progress persists for both seats',()=>{
 let s=game(undefined,undefined,{captureThreshold:100});add(s,'stonewall_heavy');add(s,'bruiser_brawler',1);s.territories[3].progress=[3,7];let r=end(end(s).state);s=r.state;assert.deepEqual(s.territories[3].progress,[7,7]);assert.deepEqual(r.events.filter(e=>e.type==='pressure').map(e=>e.amount),[4,0]);assert.deepEqual(s.stats.presenceGenerated,[4,0]);
 s.units[0].cardId='stonewall_rifles';r=end(end(s).state);assert.deepEqual(r.state.territories[3].progress,[7,7]);assert.deepEqual(r.events.filter(e=>e.type==='pressure').map(e=>e.amount),[0,0]);
});
test('destroyed first-window forces do not contribute to Turn End',()=>{
 let s=game(undefined,undefined,{captureThreshold:4});const a=add(s,'stonewall_medic',0,3,{damage:4});s=end(s).state;const h=hand(s,'bruiser_bombard');s=act(s,{type:'order',handUid:h.uid,targetUid:a.uid}).state;s=end(s).state;assert.equal(s.contested,3);assert.deepEqual(s.territories[3].progress,[0,0]);
});
test('Turn-End capture retreats survivors, destroys immobile assets, breaks through once and leaves contiguous frontline',()=>{
 let s=game(undefined,undefined,{captureThreshold:1});const a=add(s,'stonewall_heavy'),b=add(s,'bruiser_brawler',1),asset=add(s,'bruiser_banner',1);add(s,'stonewall_heavy',0,3);const r=end(end(s).state);s=r.state;assert.equal(s.territories[3].owner,0);assert.equal(s.contested,4);assert.equal(r.events.filter(e=>e.type==='capture').length,1);assert.equal(unit(s,b.uid).territory,4);assert.equal(unit(s,asset.uid),undefined);assert.equal(unit(s,a.uid).territory,4);assert.deepEqual(s.territories.map(t=>t.progress),Array.from({length:7},()=>[0,0]));
});
test('no legal retreat causes enemy-provenance destruction, with no stranded survivors',()=>{
 let s=game(undefined,undefined,{captureThreshold:1});add(s,'stonewall_heavy');const b=add(s,'bruiser_brawler',1);for(let i=0;i<5;i++)add(s,'bruiser_brawler',1,4);const r=end(end(s).state);assert.equal(unit(r.state,b.uid),undefined);assert.ok(r.events.some(e=>e.type==='death'&&e.uid===b.uid&&e.cause==='displacementFailure'));E.assertInvariants(r.state);
});
test('home victory completes Turn cleanup once and never starts another window/draw',()=>{
 let s=game(undefined,undefined,{captureThreshold:1});s.contested=6;s.territories.forEach((t,i)=>t.owner=i<6?0:1);add(s,'stonewall_heavy',0,6);const first=end(s);s=first.state;const beforeHands=s.players.map(p=>p.hand.length);const r=end(s);s=r.state;assert.equal(s.winner,0);assert.equal(s.phase,'MATCH_END');assert.equal(s.turn,1);assert.equal(s.windowIndex,2);assert.equal(s.lastResolvedTurn,1);assert.deepEqual(s.players.map(p=>p.hand.length),beforeHands);assert.equal(r.events.filter(e=>e.type==='turnEndComplete').length,1);assert.equal(r.events.some(e=>e.type==='windowStarted'||e.type==='turnStarted'||e.type==='draw'),false);assert.equal(E.dispatch(s,{type:'endTurn'}).ok,false);
});
test('deployment stamps do not age during opponent same-Turn window; Rush explicitly permits its own deployment attack',()=>{
 let s=game();const h=hand(s,'stonewall_rifles'),enemy=add(s,'bruiser_brawler',1);s=act(s,{type:'deploy',handUid:h.uid,territory:2}).state;s=act(s,{type:'move',unitUid:h.uid,territory:3}).state;unit(s,h.uid).ready=true;assert.match(E.validate(s,{type:'attack',unitUid:h.uid,targetUid:enemy.uid}),/newly deployed/i);s=end(s).state;assert.equal(unit(s,h.uid).deployedTurn,s.turn);assert.equal(unit(s,h.uid).deployedWindow,1);s=end(s).state;assert.equal(E.validate(s,{type:'attack',unitUid:h.uid,targetUid:enemy.uid}),null);
 s=game(['bruiser','stonewall']);const rush=hand(s,'bruiser_assault'),target=add(s,'stonewall_rifles',1);s=act(s,{type:'deploy',handUid:rush.uid,territory:2}).state;s=act(s,{type:'move',unitUid:rush.uid,territory:3}).state;unit(s,rush.uid).ready=true;assert.equal(E.validate(s,{type:'attack',unitUid:rush.uid,targetUid:target.uid}),null);
});
test('Mobile first move uses a window stamp; later moves exhaust and next own window refreshes exactly once',()=>{
 let s=game(),u=add(s,'stonewall_pathfinder',0,1);s=act(s,{type:'move',unitUid:u.uid,territory:2}).state;assert.equal(unit(s,u.uid).ready,true);assert.equal(unit(s,u.uid).movedWindow,1);s=act(s,{type:'move',unitUid:u.uid,territory:3}).state;assert.equal(unit(s,u.uid).ready,false);s=end(end(s).state).state;s=act(s,{type:'move',unitUid:u.uid,territory:2}).state;assert.equal(unit(s,u.uid).ready,true);assert.equal(unit(s,u.uid).movedWindow,3);
});
test('paid ability is once per Action Window and cannot activate on non-Rush deployment window',()=>{
 let s=game(),u=add(s,'stonewall_field_mechanic'),target=add(s,'stonewall_heavy',0,3,{damage:4});s=act(s,{type:'ability',unitUid:u.uid,abilityId:'repair',targetUid:target.uid}).state;assert.equal(unit(s,u.uid).abilityWindow,1);unit(s,u.uid).ready=true;assert.match(E.validate(s,{type:'ability',unitUid:u.uid,abilityId:'repair',targetUid:target.uid}),/used/);s=end(end(s).state).state;unit(s,target.uid).damage=2;assert.equal(E.validate(s,{type:'ability',unitUid:u.uid,abilityId:'repair',targetUid:target.uid}),null);
 const h=hand(s,'stonewall_field_mechanic');s=act(s,{type:'deploy',handUid:h.uid,territory:2}).state;assert.match(E.validate(s,{type:'ability',unitUid:h.uid,abilityId:'repair',targetUid:target.uid}),/newly deployed/i);
});
for(const [faction,id,kind,enemy,extra]of [['stonewall','stonewall_dig_in','cover',false,{}],['nightwalker','nightwalker_vanish','dodge',false,{}],['syndicate','syndicate_target_package','exposed',true,{}],['nightwalker','nightwalker_smoke_screen','smoke',false,{territory:3}],['bruiser','bruiser_assault_charge','attackBoost',false,{}]])test(kind+' expires at next affected owner window start, not paired Turn boundary',()=>{
 let s=game([faction,faction==='bruiser'?'stonewall':'bruiser']);const own=add(s,D.DECKS[faction].find(id=>D.CARDS[id].type==='unit')),target=enemy?add(s,'bruiser_brawler',1):own;const action=kind==='smoke'?extra:{targetUid:target.uid};s=order(s,id,action).state;const status=s.effects.find(f=>f.kind===kind);assert.equal(status.expires.windowIndex,enemy?2:3);s=end(s).state;if(enemy)assert.equal(s.effects.some(f=>f.kind===kind),false);else{assert.equal(s.effects.some(f=>f.kind===kind),true);s=end(s).state;assert.equal(s.effects.some(f=>f.kind===kind),false);}
});
for(const seat of [0,1])test('Suppression affects exactly the next target opportunity from source seat '+seat,()=>{
 let s=game(seat===0?['rogue','bruiser']:['bruiser','rogue']);if(seat===1)s=end(s).state;const target=add(s,'bruiser_brawler',1-seat);s=order(s,'rogue_make_it_work',{mode:'suppress',targetUid:target.uid}).state;const expiry=s.effects[0].expires.windowIndex;assert.equal(expiry,s.windowIndex+1);s=end(s).state;assert.equal(s.effects.some(f=>f.kind==='suppression'),true);assert.match(E.validate(s,{type:'move',unitUid:target.uid,territory:target.owner===0?2:4}),/Suppression/);const r=end(s);assert.equal(r.state.effects.some(f=>f.kind==='suppression'),false);assert.ok(r.events.some(e=>e.type==='statusExpired'&&e.phase==='WINDOW_END'&&e.expiryBasis==='actionWindow'));
});
test('Mark/Reinforce/Sabotage and temporary Presence remain owner-start effects',()=>{
 let s=game(['syndicate','stonewall']),own=add(s,'syndicate_enforcer'),enemy=add(s,'stonewall_rifles',1);s=order(s,'syndicate_target_designator',{targetUid:enemy.uid}).state;s=order(s,'syndicate_cover_protocol',{targetUid:own.uid}).state;s=order(s,'syndicate_signal_lock',{targetUid:enemy.uid}).state;assert.equal(unit(s,enemy.uid).markedUntilWindow,2);assert.equal(unit(s,own.uid).reinforcedUntilWindow,3);assert.equal(unit(s,enemy.uid).suppressedUntilWindow,2);s=end(s).state;assert.equal(unit(s,enemy.uid).marked,undefined);assert.equal(unit(s,enemy.uid).suppressed,undefined);assert.equal(unit(s,own.uid).reinforced,1);s=end(s).state;assert.equal(unit(s,own.uid).reinforced,undefined);
});
test('Hold Fast uses immediately previous enemy window and pressure survives FIRST until Turn End',()=>{
 let s=game(['bruiser','stonewall'],undefined,{captureThreshold:100});const a=add(s,'bruiser_brawler'),b=add(s,'stonewall_defender',1),ally=add(s,'stonewall_rifles',1);s=attack(s,a,b).state;s=end(s).state;assert.equal(unit(s,b.uid).defendedWindow,1);s=order(s,'stonewall_hold_fast',{territory:3}).state;assert.equal(s.effects.find(f=>f.kind==='pressure').expires.timing,'turnEnd');const r=end(s);assert.equal(r.state.effects.some(f=>f.kind==='pressure'),false);assert.ok(r.events.some(e=>e.type==='pressure'&&e.player===1&&e.pressure===11));
 // FIRST seat defended in the previous Turn's SECOND window.
 s=game(undefined,undefined,{captureThreshold:100});const defender=add(s,'stonewall_defender'),support=add(s,'stonewall_rifles'),attacker=add(s,'bruiser_brawler',1);s=end(s).state;s=attack(s,attacker,defender).state;s=end(s).state;s=order(s,'stonewall_hold_fast',{territory:3}).state;assert.equal(s.effects.some(f=>f.kind==='pressure'),true);s=end(s).state;assert.equal(s.effects.some(f=>f.kind==='pressure'),true);assert.equal(E.captureOutlook(s).pressures[0].tacticalBonus,2);s=end(s).state;assert.equal(s.effects.some(f=>f.kind==='pressure'),false);
});
test('tactical pressure cannot capture without surviving friendly objective occupation',()=>{
 let s=game(undefined,undefined,{captureThreshold:1});s.effects.push({id:'effect999',kind:'pressure',owner:0,territory:3,targetUid:null,sourcePlayer:0,sourceCardId:'stonewall_hold_fast',sourceUid:null,startedTurn:1,startedWindow:1,amount:2,stack:'refresh',consume:'expiry',expires:{timing:'turnEnd',player:0,turn:1},metadata:{}});assert.equal(E.captureOutlook(s).pressures[0].total,0);s=end(end(s).state).state;assert.equal(s.contested,3);assert.equal(s.effects.length,0);
});
test('Overwatch lasts to source next window, consumes once on voluntary entry and cannot double with attack',()=>{
 let s=game();const watch=add(s,'stonewall_bastion_gunner');s=act(s,{type:'overwatch',unitUid:watch.uid}).state;s=end(s).state;const entrant=add(s,'bruiser_brawler',1,4);const r=act(s,{type:'move',unitUid:entrant.uid,territory:3});s=r.state;assert.equal(unit(s,entrant.uid).damage,2);assert.equal(s.effects.some(f=>f.kind==='overwatch'),false);assert.equal(r.events.filter(e=>e.type==='overwatchTriggered').length,1);
});
test('Scavenge and Nothing Wasted share one eligible casualty draw across both windows and reset only next paired Turn',()=>{
 let s=game(['bruiser','rogue']);const attacker=add(s,'bruiser_heavy'),source=add(s,'rogue_broker',1),first=add(s,'rogue_scrapper',1,3,{damage:4});const n=s.players[1].hand.length;s=attack(s,attacker,first).state;assert.equal(s.players[1].hand.length,n+1);assert.equal(s.players[1].scavengedTurn,1);s=end(s).state;const target=add(s,'bruiser_heavy',0,3,{damage:4});unit(s,source.uid).damage=4;s=attack(s,source,target).state;assert.equal(s.players[1].hand.length,n+2); // Only its ordinary Window Start draw, no second casualty dividend.
 assert.equal(s.players[1].scavengedTurn,1);s=end(s).state;const victim=add(s,'rogue_scrapper',1,3,{damage:4}),killer=add(s,'bruiser_heavy');const before=s.players[1].hand.length;s=attack(s,killer,victim).state;assert.equal(s.players[1].hand.length,before+1);assert.equal(s.players[1].scavengedTurn,2);
});
test('Sacrifice and reclaim preserve exclusion, real destroyed cost and retained wounds',()=>{
 let s=game(['rogue','stonewall']),source=add(s,'rogue_broker'),cost=add(s,'rogue_scrapper',0,3,{damage:2}),target=add(s,'rogue_scrapper',0,3,{damage:2});const before=s.players[0].hand.length;s=order(s,'rogue_strip_it_for_parts',{sacrificeUid:cost.uid,targetUid:target.uid}).state;assert.equal(s.players[0].hand.length,before);assert.equal(s.players[0].scavengedTurn,undefined);assert.equal(unit(s,cost.uid),undefined);unit(s,target.uid).damage=2;s=order(s,'rogue_reclaim',{targetUid:target.uid}).state;const reclaimed=s.players[0].hand.find(h=>h.uid===target.uid);assert.equal(reclaimed.damage,2);s=act(s,{type:'deploy',handUid:target.uid,territory:2}).state;assert.equal(unit(s,target.uid).damage,2);assert.equal(unit(s,target.uid).deployedWindow,1);
});
test('Marshal successful defense lasts through next own window end; active lasts current window only',()=>{
 let s=game(['bruiser','stonewall'],[undefined,'commander_stonewall_marshal']),a=add(s,'bruiser_brawler'),b=add(s,'stonewall_defender',1);s=attack(s,a,b).state;assert.equal(unit(s,b.uid).commanderCounterUntilWindow,2);s=end(s).state;assert.equal(unit(s,b.uid).commanderCounter,1);s=end(s).state;assert.equal(unit(s,b.uid).commanderCounter,undefined);
 s=game(['stonewall','bruiser'],['commander_stonewall_marshal']);const u=add(s,'stonewall_rifles',0,2,{ready:false});s=act(s,{type:'commander',targetUid:u.uid}).state;assert.equal(unit(s,u.uid).commanderCounterUntilWindow,1);s=end(s).state;assert.equal(unit(s,u.uid).commanderCounter,undefined);
});
test('Breaker surviving Rush/Mobile bonus is evaluated at Turn End; active Attack boost expires own window',()=>{
 let s=game(['bruiser','stonewall']);const u=add(s,'bruiser_assault');s=act(s,{type:'commander',targetUid:u.uid}).state;assert.equal(unit(s,u.uid).commanderBreachUntilWindow,1);s=end(s).state;assert.equal(unit(s,u.uid).commanderBreach,undefined);assert.equal(E.captureOutlook(s).pressures[0].bonus,2);s=E.debug(s,{type:'destroy',unitUid:u.uid});assert.equal(E.captureOutlook(s).pressures[0].bonus,0);s=end(s).state;assert.equal(s.stats.presenceGenerated[0],0);
});
for(const id of Catalog.list().map(c=>c.id))test('Commander '+id+' active, once-match state and window timing serialize',()=>{
 const c=Catalog.get(id),other=c.faction==='bruiser'?'stonewall':'bruiser';let s=game([c.faction,other],[id]);const ownId=D.DECKS[c.faction].find(id=>D.CARDS[id].type==='unit'),enemyId=D.DECKS[other].find(id=>D.CARDS[id].type==='unit');add(s,ownId,0,3,{damage:1,ready:false});add(s,ownId,0,2,{damage:1});add(s,enemyId,1,3,{damage:1});s.players[0].discard.push(ownId);s.players[0].spent=4;const action=E.legalActions(s).find(a=>a.type==='commander');assert.ok(action,c.name);const r=act(s,action);assert.deepEqual(act(clone(s),action),r);s=r.state;assert.equal(s.players[0].commander.used,true);assert.equal(E.legalActions(s).some(a=>a.type==='commander'),false);s=end(end(s).state).state;assert.equal(s.players[0].commander.used,true);assert.ok(s.players[0].commander.passiveWindow>=-1);assert.doesNotMatch(E.commanders.get(id).passive.text,/offensive turn|global turn/);const old=B.createRuntime('sprint12');assert.deepEqual(old.engine.commanders.get(id),require('../docs/balance/sprint15-v1.2.0-baseline/source/commanders.js').get(id));
});
test('all 155 cards can enter or resolve through a legal authoritative action',()=>{
 let count=0;for(const card of Object.values(D.CARDS)){
  const other=card.faction==='bruiser'?'stonewall':'bruiser';let s;
  if(card.type!=='order'){s=game([card.faction,other]);const h=hand(s,card.id);const r=act(s,{type:'deploy',handUid:h.uid,territory:2});assert.equal(r.state.players[0].hand.some(x=>x.uid===h.uid),false);assert.ok(r.state.units.some(x=>x.uid===h.uid));count++;continue;}
  if(card.timing==='response'){s=game([other,card.faction]);const a=add(s,D.DECKS[other].find(id=>D.CARDS[id].type==='unit')),b=add(s,D.DECKS[card.faction].find(id=>D.CARDS[id].type==='unit'),1);const h=hand(s,card.id,1);s=act(s,{type:'attack',unitUid:a.uid,targetUid:b.uid}).state;act(s,{type:'respond',handUid:h.uid});count++;continue;}
  if(card.timing==='counter'){s=game([card.faction,'stonewall']);const a=add(s,'syndicate_enforcer'),b=add(s,'stonewall_defender',1),brace=hand(s,'stonewall_brace',1),h=hand(s,card.id);s=act(s,{type:'attack',unitUid:a.uid,targetUid:b.uid}).state;s=act(s,{type:'respond',handUid:brace.uid}).state;act(s,{type:'counter',handUid:h.uid});count++;continue;}
  s=game([card.faction,other]);const ownId=D.DECKS[card.faction].find(id=>D.CARDS[id].type==='unit'),enemyId=D.DECKS[other].find(id=>D.CARDS[id].type==='unit');add(s,ownId,0,3,{damage:1,ready:false,defendedWindow:0});add(s,ownId,0,3,{damage:1});add(s,D.DECKS[card.faction].find(id=>D.CARDS[id].type==='leader'),0,3,{damage:1});add(s,enemyId,1,3,{damage:1});const h=hand(s,card.id);const action=E.legalActions(s).find(a=>a.type==='order'&&a.handUid===h.uid);assert.ok(action,card.id+' has a legal effect');act(s,action);count++;
 }assert.equal(count,155);
});

test('Quartermaster first qualifying Order gate resets on next own window, not SECOND or response',()=>{
 let s=game(['syndicate','bruiser'],['commander_syndicate_quartermaster']),h=hand(s,'syndicate_disrupt');assert.equal(E.actionCost(s,{type:'order',handUid:h.uid}).commandActions,0);s=act(s,{type:'order',handUid:h.uid}).state;assert.equal(s.players[0].commander.passiveWindow,1);h=hand(s,'syndicate_disrupt');assert.equal(E.actionCost(s,{type:'order',handUid:h.uid}).commandActions,1);s=act(s,{type:'order',handUid:h.uid}).state;s=end(s).state;assert.equal(s.players[0].commander.passiveWindow,1);s=end(s).state;h=hand(s,'syndicate_disrupt');assert.equal(E.actionCost(s,{type:'order',handUid:h.uid}).commandActions,0);
});
test('Ghost first Precision deployment is one protected entry per own Action Window',()=>{
 let s=game(['nightwalker','bruiser']);const a=hand(s,'nightwalker_blade'),b=hand(s,'nightwalker_blade');s=act(s,{type:'deploy',handUid:a.uid,territory:2}).state;s=act(s,{type:'deploy',handUid:b.uid,territory:2}).state;assert.equal(unit(s,a.uid).reinforced,1);assert.equal(unit(s,b.uid).reinforced,undefined);assert.equal(s.players[0].commander.passiveWindow,1);s=end(s).state;assert.equal(unit(s,a.uid).reinforced,1);s=end(s).state;assert.equal(unit(s,a.uid).reinforced,undefined);const c=hand(s,'nightwalker_blade');s=act(s,{type:'deploy',handUid:c.uid,territory:2}).state;assert.equal(unit(s,c.uid).reinforced,1);assert.equal(s.players[0].commander.passiveWindow,3);
});
test('Saboteur and Drifter first-event gates use window stamps while enemy spending clears at enemy start',()=>{
 let s=game(['nightwalker','stonewall'],['commander_nightwalker_saboteur']),a=add(s,'stonewall_rifles',1),b=add(s,'stonewall_rifles',1);s=order(s,'nightwalker_blackout',{targetUid:a.uid}).state;assert.equal(s.players[1].spent,1);s=order(s,'nightwalker_blackout',{targetUid:b.uid}).state;assert.equal(s.players[1].spent,1);s=end(s).state;assert.equal(s.players[1].spent,0);assert.equal(s.players[0].commander.passiveWindow,1);
 s=game(['rogue','stonewall'],['commander_rogue_drifter']);const u=add(s,'rogue_outrider',0,1);assert.equal(E.actionCost(s,{type:'move',unitUid:u.uid,territory:2}).commandActions,0);s=act(s,{type:'move',unitUid:u.uid,territory:2}).state;assert.equal(E.actionCost(s,{type:'move',unitUid:u.uid,territory:3}).commandActions,1);s=end(end(s).state).state;assert.equal(E.actionCost(s,{type:'move',unitUid:u.uid,territory:3}).commandActions,0);
});
test('Warden and Medic fire at their own start once; Sabotage cleanup precedes printed onStart',()=>{
 let s=game();const medic=add(s,'stonewall_medic',0,2,{damage:3}),ally=add(s,'stonewall_rifles',0,2,{damage:3});s=end(s).state;assert.equal(unit(s,ally.uid).damage,3);const r=end(s);s=r.state;assert.equal(unit(s,ally.uid).damage,1);assert.equal(unit(s,medic.uid).damage,1);assert.equal(r.events.filter(e=>e.type==='commanderPassive'&&e.targetUid===ally.uid).length,1);
 s=game(['nightwalker','stonewall'],['commander_nightwalker_saboteur']);const hardpoint=add(s,'stonewall_hardpoint',1),target=add(s,'stonewall_rifles',1,3,{damage:1});hardpoint.suppressed=true;hardpoint.suppressedUntilWindow=2;s=end(s).state;assert.equal(unit(s,hardpoint.uid).suppressed,undefined);assert.ok(s.effects.some(f=>f.kind==='cover'&&f.targetUid===target.uid));
});
test('eligible displacement casualty shares the already-used paired casualty draw allowance',()=>{
 let s=game(['bruiser','rogue'],undefined,{captureThreshold:1});const victim=add(s,'rogue_scrapper',1,3,{damage:4}),killer=add(s,'bruiser_heavy');s=attack(s,killer,victim).state;assert.equal(s.players[1].scavengedTurn,1);add(s,'bruiser_rupture_heavy');const asset=add(s,'rogue_workshop',1);s=end(s).state;const n=s.players[1].hand.length;const r=end(s);assert.equal(unit(r.state,asset.uid),undefined);assert.equal(r.state.players[1].hand.length,n);assert.equal(r.state.players[1].scavengedTurn,1);assert.ok(r.events.some(e=>e.type==='death'&&e.uid===asset.uid&&e.cause==='displacementFailure'));
});
test('simultaneous lethal Scavenge source cannot claim casualty credit before removal',()=>{
 let s=game(['bruiser','rogue'],[undefined,'commander_rogue_drifter']);const source=add(s,'rogue_broker',1,3,{damage:4}),victim=add(s,'rogue_scrapper',1,3,{damage:4});const n=s.players[1].hand.length;s=order(s,'bruiser_frag_out',{territory:3}).state;assert.equal(unit(s,source.uid),undefined);assert.equal(s.players[1].hand.length,n);assert.equal(s.players[1].scavengedTurn,undefined);
});
